### ISSUE TITLE
Could you please list the hyper-parameters for Squirrel & Chameleon?

### ISSUE THREAD

**Issue by ChenJY-Count** [mtang724/NWR-GAE#2]
Thanks for your excellent work, it inspires me a lot.
However , when I use the default hyper-parameters to run the dataset Chameleon & Squirrel,
I can not  reproduce the result shown in the original paper, which is above 70% and 60% respectively.
So could you please list the hyper-parameters chosen for Squirrel & Chameleon?
Thanks again.

**Comment by mtang724** [comment]
Hi, thank you so much for your question.
I've uploaded the latest version of the code, could you please try again? I can get above 70% and 60% results respectively on the current version with default settings. Thank you again, please let me know if you have further questions.

**Comment by ChenJY-Count** [comment]
Thanks for your detailed reply!
It really helps me a lot, and the default setting works well on the two datasets.
Thanks again!
